### ISSUE TITLE
ATK Speed / Multiple SP

### ISSUE THREAD

**Issue by MawMawLon** [JMBQ/Honkai_Impact_3rd_menu_mod#37]
These 2 mod doesn't work properly on 6.8.0 Mod Menu Sea
is adding damage mod in mod menu high risk?
also what if i use the mod in non rooted phone as is? no vm.

**Comment by JMBQ** [comment]
menu mod does not require ROOT. 
AS/SP are not invalid. 
You did not strictly test them.

**Comment by MawMawLon** [comment]
Can you check again please?
ATK Speed only works for some characters ( Herscher of Thunder )
SP Multiple doesn't do anything in for me in story mode.

**Comment by JMBQ** [comment]
As long as the game version remains unchanged, the function will not fail. Because I tested it before release and the version has not changed, then the core code of the game will remain unchanged and the function will definitely take effect.  Don't continue to care about it, because the character you choose may not be suitable for AS, and SP is not important. 2x is too low for you, and you can't feel it.

**Comment by MawMawLon** [comment]
Ok thank you for clarifying it
