### ISSUE TITLE
7.3版本

### ISSUE THREAD

**Issue by gab235846170** [JMBQ/Honkai_Impact_3rd_menu_mod#51]
大佬你好 謝謝你一直以來的分享
想請問你也會上傳7.3版本的各區服apks嗎?

**Comment by JMBQ** [comment]
7.3.0不会制作其他区服的apks，7.2.0是因为碰上新年版本才会如此。

如果你们需要其他区服的mod，我可以提供制作办法给某个人，由他来制作发布，要求：

* 稍微懂一些计算机常识，能够通过搜索引擎来处理一些常见问题
* 只需要简单的添加替换文件，修改文本就可以制作出Mod
* 知道如何发布mod，发布在哪个平台，下载链接又是哪个网盘平台等
* 在游戏更新版本7天内自行测试并发布

如果谁有兴趣并且符合上述4个要求，可以稍微描述下自己并留下email

##
7.3.0 will not be making apks for other zones, 7.2.0 is doing so because it happens to be a new year's release.

If you need mods for other servers, I can provide a way to make them to someone who will build and release them, requirements:

* A little bit of computer literacy, and the ability to deal with common problems through search engines.
* Simply add and replace files, and modify text to make a mod.
* Know how to release the mod, which platform to release it on, and which online disk platform to download the link to.
* Test and release the mod within 7 days of the game update.

If anyone is interested and meets the above 4 requirements, please describe yourself a bit and leave an email

**Comment by Rempacious** [comment]
> 7.3.0不会制作其他区服的apks，7.2.0是因为碰上新年版本才会如此。
> 
> 如果你们需要其他区服的mod，我可以提供制作办法给某个人，由他来制作发布，要求：
> 
> * 稍微懂一些计算机常识，能够通过搜索引擎来处理一些常见问题
> * 只需要简单的添加替换文件，修改文本就可以制作出Mod
> * 知道如何发布mod，发布在哪个平台，下载链接又是哪个网盘平台等，如果你之前发布过其他mod，那更好
> * 在游戏更新版本7天内自行测试并发布
> 
> 如果谁有兴趣并且符合上述4个要求，可以稍微描述下自己并留下email
> 
> 7.3.0 will not be making apks for other zones, 7.2.0 is doing so because it happens to be a new year's release.
> 
> If you need mods for other servers, I can provide a way to make them to someone who will build and release them, requirements:
> 
> * A little bit of computer literacy, and the ability to deal with common problems through search engines.
> * Simply add and replace files, and modify text to make a mod.
> * Know how to release the mod, which platform to release it on, and which online disk platform to download the link to, If you've released other mods before, all the better!.
> * Test and release the mod within 7 days of the game update.
> 
> If anyone is interested and meets the above 4 requirements, please describe yourself a bit and leave an email

I could help with releasing to other regions. I already established a community and the users want other regions as well.

**Comment by JMBQ** [comment]
> I could help with releasing to other regions. I already established a community and the users want other regions as well.

Leave the platform link and email, and I will contact you via email.

**Comment by Rempacious** [comment]
> > I could help with releasing to other regions. I already established a community and the users want other regions as well.
> 
> Leave the platform link and email, and I will contact you via email.

Community links: https://discord.gg/WVJD3scg and https://waa.ai/HonkaiJMBQ
Email: rempacious@gmail.com

**Comment by JMBQ** [comment]
OK

**Comment by gab235846170** [comment]
> 7.3.0不会制作其他区服的apks，7.2.0是因为碰上新年版本才会如此。
> 
> 如果你们需要其他区服的mod，我可以提供制作办法给某个人，由他来制作发布，要求：
> 
> * 稍微懂一些计算机常识，能够通过搜索引擎来处理一些常见问题
> * 只需要简单的添加替换文件，修改文本就可以制作出Mod
> * 知道如何发布mod，发布在哪个平台，下载链接又是哪个网盘平台等，如果你之前发布过其他mod，那更好
> * 在游戏更新版本7天内自行测试并发布
> 
> 如果谁有兴趣并且符合上述4个要求，可以稍微描述下自己并留下email
> 
> 7.3.0 will not be making apks for other zones, 7.2.0 is doing so because it happens to be a new year's release.
> 
> If you need mods for other servers, I can provide a way to make them to someone who will build and release them, requirements:
> 
> * A little bit of computer literacy, and the ability to deal with common problems through search engines.
> * Simply add and replace files, and modify text to make a mod.
> * Know how to release the mod, which platform to release it on, and which online disk platform to download the link to, If you've released other mods before, all the better!.
> * Test and release the mod within 7 days of the game update.
> 
> If anyone is interested and meets the above 4 requirements, please describe yourself a bit and leave an email


了解了謝謝大佬
不過我沒有這方面的能力orz
只能等看看其他有能力的大佬了
